import { NextRequest, NextResponse } from "next/server";

/**
 * Strict CSP with per-request nonce (PCI-friendly).
 *
 * Next.js will automatically apply the nonce to:
 * - Framework/runtime scripts
 * - Inline scripts/styles generated by Next.js
 * - <Script> components when given the nonce prop
 *
 * IMPORTANT: Pages must be dynamically rendered for nonce injection to work.
 */
export function proxy(request: NextRequest) {
  const nonce = Buffer.from(crypto.randomUUID()).toString("base64");
  const isDev = process.env.NODE_ENV === "development";

  const cspHeader = `
    default-src 'self';
    base-uri 'self';
    form-action 'self';
    frame-ancestors 'none';
    object-src 'none';
    script-src 'self' 'nonce-${nonce}' 'strict-dynamic' https://www.googletagmanager.com${isDev ? " 'unsafe-eval'" : ""};
    style-src 'self' 'nonce-${nonce}';
    img-src 'self' blob: data: https://res.cloudinary.com https://images.unsplash.com;
    font-src 'self' data: https:;
    connect-src 'self' https: wss:;
    upgrade-insecure-requests;
  `;

  // Replace extra whitespace.
  const contentSecurityPolicyHeaderValue = cspHeader.replace(/\s{2,}/g, " ").trim();

  const requestHeaders = new Headers(request.headers);
  requestHeaders.set("x-nonce", nonce);
  requestHeaders.set("Content-Security-Policy", contentSecurityPolicyHeaderValue);

  const response = NextResponse.next({
    request: {
      headers: requestHeaders,
    },
  });

  response.headers.set("Content-Security-Policy", contentSecurityPolicyHeaderValue);
  return response;
}

export const config = {
  matcher: [
    {
      // Match all request paths except for:
      // - api (API routes)
      // - _next/static (static files)
      // - _next/image (image optimization files)
      // - favicon.ico (favicon file)
      source: "/((?!api|_next/static|_next/image|favicon.ico).*)",
      missing: [
        { type: "header", key: "next-router-prefetch" },
        { type: "header", key: "purpose", value: "prefetch" },
      ],
    },
  ],
};

