import { NextRequest, NextResponse } from "next/server";

// Login rate limiting (per-instance; use Redis in production for multi-instance)
const loginAttempts = new Map<string, { count: number; resetAt: number }>();
const LOGIN_WINDOW_MS = 15 * 60 * 1000; // 15 minutes
const MAX_LOGIN_ATTEMPTS = 10;

function getClientIp(request: NextRequest): string {
  const forwarded = request.headers.get("x-forwarded-for");
  const realIp = request.headers.get("x-real-ip");
  if (forwarded) return forwarded.split(",")[0].trim();
  if (realIp) return realIp.trim();
  return "unknown";
}

function isLoginRoute(pathname: string): boolean {
  return (
    pathname === "/login" ||
    pathname.startsWith("/api/send-login-verification-code") ||
    pathname.startsWith("/api/verify-login-verification-code")
  );
}

function checkLoginRateLimit(ip: string): { allowed: boolean; retryAfter?: number } {
  const now = Date.now();
  const entry = loginAttempts.get(ip);
  if (!entry) {
    loginAttempts.set(ip, { count: 1, resetAt: now + LOGIN_WINDOW_MS });
    return { allowed: true };
  }
  if (entry.resetAt < now) {
    loginAttempts.set(ip, { count: 1, resetAt: now + LOGIN_WINDOW_MS });
    return { allowed: true };
  }
  if (entry.count >= MAX_LOGIN_ATTEMPTS) {
    return { allowed: false, retryAfter: Math.ceil((entry.resetAt - now) / 1000) };
  }
  entry.count += 1;
  return { allowed: true };
}

/**
 * Strict CSP with per-request nonce (PCI-friendly).
 * Also includes lightweight edge WAF-style request blocking for common probes.
 * Login rate limiting for POST to /login and login verification APIs.
 *
 * Next.js will automatically apply the nonce to:
 * - Framework/runtime scripts
 * - Inline scripts/styles generated by Next.js
 * - <Script> components when given the nonce prop
 *
 * IMPORTANT: Pages must be dynamically rendered for nonce injection to work.
 */
export function proxy(request: NextRequest) {
  const pathname = request.nextUrl.pathname;

  // Login rate limit: POST to login page or login verification APIs
  if (request.method === "POST" && isLoginRoute(pathname)) {
    const ip = getClientIp(request);
    const { allowed, retryAfter } = checkLoginRateLimit(ip);
    if (!allowed) {
      return NextResponse.json(
        { error: "Too many attempts. Please try again later.", retryAfter },
        { status: 429, headers: { "Retry-After": String(retryAfter ?? 900) } }
      );
    }
  }

  // ---------------------------------------------------------------------------
  // Lightweight WAF-style blocks (best-effort).
  // Note: A managed WAF (Cloudflare/AWS/Vercel) is still recommended for compliance
  // detection + bot mitigation + rate limiting.
  // ---------------------------------------------------------------------------
  const block = getWafBlock(request);
  if (block) {
    return new NextResponse("Forbidden", {
      status: 403,
      headers: {
        "Cache-Control": "no-store",
        "Content-Type": "text/plain; charset=utf-8",
        "X-WAF-Blocked": "1",
        "X-WAF-Rule": block.rule,
      },
    });
  }

  const nonce = randomBase64Nonce(16);
  const isDev = process.env.NODE_ENV === "development";

  const scriptSrcExtras = isDev ? " 'unsafe-eval'" : "";
  const cspHeader = `
    default-src 'self';
    base-uri 'self';
    form-action 'self';
    frame-ancestors 'self';
    object-src 'none';
    script-src 'self' 'nonce-${nonce}' 'strict-dynamic' https://www.googletagmanager.com https://pagead2.googlesyndication.com https://js.paystack.co https://www.google.com https://www.gstatic.com https://www.recaptcha.net${scriptSrcExtras};
    style-src 'self' 'nonce-${nonce}' 'unsafe-inline' https://fonts.googleapis.com;
    img-src 'self' data: blob: https: https://res.cloudinary.com https://images.unsplash.com https://ui-avatars.com https://*.supabase.co https://*.supabase.in https://upload.wikimedia.org https://www.google.com https://www.gstatic.com https://www.recaptcha.net https://jobicy.com https://*.jobicy.com https://remotive.com https://*.remotive.com https://remoteok.com https://*.remoteok.com;
    font-src 'self' data: https://fonts.gstatic.com;
    connect-src 'self' https://*.supabase.co wss://*.supabase.co https://*.supabase.in https://www.google-analytics.com https://analytics.google.com https://www.google.com https://www.gstatic.com https://www.recaptcha.net https://api.paystack.co https://js.paystack.co https://checkout.paystack.com https://googleads.g.doubleclick.net https://pagead2.googlesyndication.com https://ep1.adtrafficquality.google https://ep2.adtrafficquality.google https://tpc.googlesyndication.com;
    frame-src 'self' https://*.supabase.co https://accounts.google.com https://www.google.com https://www.recaptcha.net https://www.gstatic.com https://checkout.paystack.com https://googleads.g.doubleclick.net https://tpc.googlesyndication.com;
    upgrade-insecure-requests;
  `;

  // Replace extra whitespace.
  const contentSecurityPolicyHeaderValue = cspHeader.replace(/\s{2,}/g, " ").trim();

  const requestHeaders = new Headers(request.headers);
  requestHeaders.set("x-nonce", nonce);
  requestHeaders.set("Content-Security-Policy", contentSecurityPolicyHeaderValue);

  const response = NextResponse.next({
    request: {
      headers: requestHeaders,
    },
  });

  response.headers.set("Content-Security-Policy", contentSecurityPolicyHeaderValue);
  return response;
}

function getWafBlock(request: NextRequest): { rule: string } | null {
  const { pathname, search } = request.nextUrl;
  const url = request.nextUrl.href;

  // Basic URL length limit to reduce abuse.
  if (url.length > 2048) return { rule: "url-length" };

  // Block common CMS/probe paths not used by this app.
  const p = pathname.toLowerCase();
  const blockedPaths = [
    "/wp-admin",
    "/wp-login.php",
    "/xmlrpc.php",
    "/phpmyadmin",
    "/.env",
    "/.git",
    "/server-status",
  ];
  if (blockedPaths.some((bp) => p === bp || p.startsWith(`${bp}/`))) return { rule: "known-probe-path" };

  // Path traversal / encoded traversal probes.
  if (p.includes("..") || p.includes("%2e%2e") || p.includes("%2f..") || p.includes("..%2f")) return { rule: "path-traversal" };

  // Simple SQLi / XSS probe patterns in query string.
  const q = decodeSafe(search).toLowerCase();
  if (q) {
    // XSS-ish
    if (q.includes("<script") || q.includes("javascript:") || q.includes("%3cscript")) return { rule: "xss-probe" };
    // SQLi-ish
    if (
      q.includes("union select") ||
      q.includes("information_schema") ||
      q.includes("sleep(") ||
      q.includes("benchmark(") ||
      q.includes("'--") ||
      q.includes("\"--") ||
      q.includes(" or 1=1") ||
      q.includes(" or '1'='1") ||
      q.includes(" or \"1\"=\"1")
    ) {
      return { rule: "sqli-probe" };
    }
  }

  // Overly large request bodies are suspicious for a mostly static marketing site.
  // (Skip if content-length is missing.)
  const cl = request.headers.get("content-length");
  if (cl) {
    const n = Number(cl);
    if (Number.isFinite(n) && n > 1_000_000) return { rule: "body-too-large" }; // 1MB
  }

  return null;
}

function decodeSafe(s: string) {
  try {
    return decodeURIComponent(s);
  } catch {
    return s;
  }
}

/** CSP nonce; Edge-safe (no Node Buffer). */
function randomBase64Nonce(byteLength: number): string {
  const bytes = new Uint8Array(byteLength);
  crypto.getRandomValues(bytes);
  let bin = "";
  for (let i = 0; i < bytes.length; i++) bin += String.fromCharCode(bytes[i]!);
  return btoa(bin);
}

export const config = {
  matcher: [
    {
      source: "/((?!api|_next/static|_next/image|favicon.ico).*)",
      missing: [
        { type: "header", key: "next-router-prefetch" },
        { type: "header", key: "purpose", value: "prefetch" },
      ],
    },
    "/api/send-login-verification-code",
    "/api/verify-login-verification-code",
    "/login",
  ],
};

